src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    
    #[Constraints\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Constraints\NotBlank]
    #[ORM\Column(type: Types::DECIMAL, precision: 16, scale: 2, nullable: true)]
    private ?string $money_balance = null;

    #[Constraints\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'team', targetEntity: Player::class)]
    private Collection $players;

    public function __construct()
    {
        $this->players = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getMoneyBalance(): ?string
    {
        return $this->money_balance;
    }

    public function setMoneyBalance(?string $money_balance): self
    {
        $this->money_balance = $money_balance;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Player>
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players->add($player);
            $player->setTeam($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): self
    {
        if ($this->players->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getTeam() === $this) {
                $player->setTeam(null);
            }
        }

        return $this;
    }
}

templates/pages/index.html.twig
{% extends 'layouts/app.html.twig' %}

{% block title %} Home {% endblock %}

{% block breadcrumbs %}
    <div class="text-cent">
       <h3>Top Richest Teams</h3>
    </div>
{% endblock %}


{% block body %}
    <div class="row p-3">
        {% for team in teams %}
            <div class="col-md-4 col-12">
                <div class="card m-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ team.name }}</h5>
                        <p class="card-text">{{ team.moneyBalance }}</p>
                        <p class="card-text">{{ team.country }}</p>
                        <p class="card-text">{{ team.players().count() }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}