src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Constraints\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Constraints\NotBlank]
    #[ORM\Column(length: 255)]
    private ?string $surname = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 16, scale: 2, nullable: true)]
    private ?string $market_value = null;

    #[ORM\ManyToOne(inversedBy: 'players')]
    private ?Team $team = null;

    #[ORM\Column]
    private ?bool $is_for_sale = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function isIsForSale(): ?bool
    {
        return $this->is_for_sale;
    }

    public function setIsForSale(bool $is_for_sale): self
    {
        $this->is_for_sale = $is_for_sale;

        return $this;
    }

    public function getMarketValue(): ?string
    {
        return $this->market_value;
    }

    public function setMarketValue(?string $market_value): self
    {
        $this->market_value = $market_value;

        return $this;
    }
}

src/Controller/TransferController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Entity\Team;
use App\Repository\PlayerRepository;
use App\Repository\TeamRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

#[Route('/transfer', name: 'app_transfer.')]
class TransferController extends AbstractController
{
    public function __construct(
        protected TeamRepository $teamRepository,
        protected PlayerRepository $playerRepository
    )
    {
    }

    #[Route('/list-players', name: 'list_players')]
    public function index(): Response
    {
        return $this->render('transfer/index.html.twig', [
            'players' => $this->playerRepository->findAll(),
            'teams' => $this->teamRepository->findAll(),
            'context' => [ ObjectNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($obj){ return $obj->getId(); }]
        ]);
    }

    #[Route('/transfer/{player}/{team}', name: 'transfer')]
    public function transfer(
        Player $player,
        Team $team,
        TeamRepository $teamRepository,
        Request $request
    ): Response
    {
        $playerTeam = $player->getTeam();

        if ((float)$team->getMoneyBalance() < (float)$player->getMarketValue()) {
            return $this->json(['status' => false, 'message' => $team->getName().' Has Insufficient Funds']);
        }

        $buyingTeamBalance = (float)$team->getMoneyBalance();
        $team->setMoneyBalance($buyingTeamBalance - (float)$player->getMarketValue());
        $team->addPlayer($player);

        $playerTeam->setMoneyBalance((float)$playerTeam->getMoneyBalance() + (float)$player->getMarketValue());

        $teamRepository->save($team, true);
        $teamRepository->save($playerTeam, true);

        return $this->json(['status' => true, 'message' => 'Player Sold to '. $team->getName()]);
    }
}

templates/transfer/index.html.twig
{% extends 'layouts/app.html.twig' %}

{% block title %}Transfer{% endblock %}

{% block breadcrumbs %}
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('app_home') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Transfer</li>
        </ol>
    </nav>
{% endblock %}

{% block body %}
    <div class="row p-3">
        {% for player in players %}
            <div class="col-md-4 col-12">
                <div class="card m-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ player.surname }}</h5>
                        <p class="card-text">{{ player.name }}</p>
                        <p class="card-text">{{ player.team.name }}</p>
                        <p class="card-text">{{ player.marketValue }}</p>
                        <a href="#" data-player-name="{{ player.name }}" data-action="buy" data-player-id="{{ player.id }}" class="btn btn-outline-primary buy-btn">Buy</a>
                        <a href="#" data-player-name="{{ player.name }}" data-action="sell" data-player-id="{{ player.id }}" class="btn btn-outline-info sell-btn">Sell</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <input hidden="" id="teams-input" data-teams="{{ teams|serialize('json', context) }}" type="text">
{% endblock %}

{% block scripts %}
    <script>

        $(".buy-btn").click(async function (item) {
            await transfer(item);
        })

        $(".sell-btn").click(async function (item) {
            await transfer(item);
        })

        async function transfer(item) {
            const element = $(item.target);

            const teams = {};

            $('#teams-input').data('teams').forEach(team => teams[team.id] = team.name)

            const selectedTeam = await Swal.fire({
                title: 'Select Team',
                input: 'select',
                inputAttributes: {
                    autocapitalize: 'off',
                    options: ['test', 'again']
                },
                inputOptions:teams,
                showCancelButton: true,
                confirmButtonText: 'Continue',
                showLoaderOnConfirm: true,
            })

            if (! selectedTeam.isConfirmed) {
                await abortFeedBack();
                return;
            }

            let url = '{{ url('app_transfer.transfer', {player: ':player-id', team: ':team-id'}) }}';

            url = url.replace(':player-id', element.data('player-id'))
                .replace(':team-id', selectedTeam.value);
            const action = element.data('action');
            const token = '{{ csrf_token('transfer') }}'


            const userFeedBack = await Swal.fire({
                title: `Are sure to ${action} player ${element.data('player-name')}`,
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Yes!'
            })

            if (! userFeedBack.isConfirmed) {
                await abortFeedBack();
                return;
            }

            const request = await fetch(url, {
                method: 'POST',
                headers: {
                    'X-CSRF-TOKEN': token,
                },
                body: {
                    action,
                }
            })

            const data = await request.json()

            if (data.status) {

                await Swal.fire({
                    title: data.message,
                    icon: 'success',
                    showClass: {
                        popup: 'animate__animated animate__fadeInDown'
                    },
                    hideClass: {
                        popup: 'animate__animated animate__fadeOutUp'
                    }
                })
            } else {
                await Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: data.message,
                    footer: '<a href="{{ path('teams.index') }}">Home</a>'
                })

                return;
            }

            document.location.reload();
        }

        async function abortFeedBack(title = null) {
            await Swal.fire({
                title: title ?? 'Action Aborted',
                html: 'closing in <b></b> milliseconds.',
                timer: 2000,
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading()
                    const b = Swal.getHtmlContainer().querySelector('b')
                    timerInterval = setInterval(() => {
                        b.textContent = Swal.getTimerLeft()
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }
            });
        }
    </script>

{% endblock %}